# Generated by Django 5.2.1 on 2025-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='order_id',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
